additional_formulas: 
  # Jira
  - jira-cli
  - jiratui

  # Java Web Server
  - tomcat
  
  # iOS
  - cocoapods
  - xcodes
  - xcenv

additional_casks:
  # Editor
  - android-studio

  # Proxy
  - proxyman
  - charles
