additional_taps: []
common_taps:
  - sst/tap
  - olets/tap
  - nikitabobko/tap
  - felixkratz/formulae

additional_formulas: []
common_formulas:
  # Core
  - ansible
  - stow
  - wget
  - parallel
  - tlrc
  - btop
  
  # Editor
  - neovim
  - tree-sitter-cli
  - luarocks

  # Version Control
  - gh
  - lazygit
  - jj
  - git-cliff
  - koji

  # AI 
  - sst/tap/opencode

  # Databases
  - lazysql

  # PubSub
  - kafkactl

  # Containers
  - docker
  - docker-buildx
  - docker-compose
  - colima
  - lima
  - lazydocker

  # AWS
  - awscli
  - aws-sam-cli

  # Kubernetes
  - k9s
  - kubernetes-cli
  - kubectx
  - helm

  # OpenAPI
  - openapi-generator 

  # Protobuf
  - protobuf
  - protoc-gen-go
  - protoc-gen-go-grpc

  # Network
  - dnsmasq
  - mkcert
  - nss
  - ifstat

  # Java Build
  - gradle
  - maven

  # Rust Toolchain
  - rustup

  # NodeJS 
  - pnpm

  # Media
  - librsvg
  - imagemagick
  - d2
  - ffmpeg

  # Finance
  - beancount

  # Writing
  - typst

  # Productivity
  - aerc
  - calcurse
  - jrnl
  - bartib

  # Asthetics
  - felixkratz/formulae/borders
  - felixkratz/formulae/sketchybar

  # Reading
  - newsboat
  - w3m

  # Terminal Search
  - jq
  - fd 
  - xq
  - fzf
  - yq
  - ripgrep
  - ripgrep-all
  - grex

  # Terminal Navigation
  - zoxide

  # Terminal Prompt
  - starship

  # Nushell
  - nushell
  - carapace 

  # Password Management
  - pass

additional_casks: []
common_casks:
  # Editor
  - intellij-idea

  # Terminal
  - ghostty

  # Music
  - spotify

  # Fonts
  - font-sketchybar-app-font
  - font-terminess-ttf-nerd-font

  # Window Manager
  - nikitabobko/tap/aerospace

additional_services: []
common_services: 
  - sketchybar
  - borders
