--when.repositories = [ "~/Code/Personal", "~/dotfiles" ]

[user]
email = "joshrasmussen34@gmail.com"
name = "Josh Hamill"

[signing]
behavior = "drop"
backend = "gpg"
key = "Josh Hamill <joshrasmussen34@gmail.com>"

[git]
sign-on-push = true
