---
- name: Remove Unwanted Formulas
  community.general.homebrew:
    state: absent
    name: "{{ unwanted_formulas }}"
  when: unwanted_formulas | length > 0

- name: Remove Unwanted Casks
  community.general.homebrew_cask:
    state: absent
    name: "{{ unwanted_casks }}"
  when: unwanted_casks | length > 0

- name: Remove Unwanted Taps
  community.general.homebrew_tap:
    state: absent
    name: "{{ unwanted_taps }}"
  when: unwanted_taps | length > 0
