---
- name: Install Editors Tools
  community.general.homebrew:
    state: present
    name:
      - neovim
      - tree-sitter-cli
      - luarocks

- name: Install VCS Tools
  community.general.homebrew:
    state: present
    name:
      - gh
      - lazygit
      - jj
      - git-cliff
      - koji

- name: Install SST OpenCode
  block:  
    - name: Add SST Tap
      community.general.homebrew_tap:
        state: present
        name: sst/tap

    - name: Install OpenCode
      community.general.homebrew:
        state: present
        name: sst/tap/opencode

- name: Install IntelliJ
  community.general.homebrew_cask:
    state: present
    name: intellij-idea
    install_options: "appdir={{ casks_appdir }}"

- name: Install Android Studio 
  community.general.homebrew_cask:
    state: present
    name: android-studio
    install_options: "appdir={{ casks_appdir }}"
