---
- name: Install Database Tools
  community.general.homebrew:
    state: present
    name:
      - lazysql
      - redis

- name: Install Container Tools
  community.general.homebrew:
    state: present
    name:
      - docker
      - docker-buildx
      - docker-compose
      - colima
      - lima
      - lazydocker

- name: Install AWS Tools
  community.general.homebrew:
    state: present
    name:
      - awscli
      - aws-sam-cli

- name: Install Kubernetes Tools
  community.general.homebrew:
    state: present
    name:
      - k9s
      - kubernetes-cli
      - kubectx
      - helm
      # - tilt
      # - k3d

- name: Install Kafka Tooling
  community.general.homebrew:
    name: kafkactl
    state: present

- name: Install OpenAPI Tooling
  community.general.homebrew:
    name: openapi-generator 
    state: present

- name: Install GRPC Tooling
  community.general.homebrew:
    state: present
    name:
      - protobuf
      - protoc-gen-go
      - protoc-gen-go-grpc

- name: Install Networking Tools
  community.general.homebrew:
    state: present
    name:
      - dnsmasq
      - mkcert
      - nss

- name: Install Proxy Tools
  community.general.homebrew_cask:
    state: present
    name: 
      - proxyman
      - charles
    install_options: "appdir={{ casks_appdir }}"
