--- 
- name: Install Fonts
  community.general.homebrew_cask:
    state: present
    name:
      - font-terminess-ttf-nerd-font
      - font-sketchybar-app-font

- name: Setup Aerospace
  block:
    - name: Add Aerospace Tap
      community.general.homebrew_tap:
        state: present
        name: nikitabobko/tap

    - name: Install Aerospace
      community.general.homebrew_cask:
        state: present
        name: nikitabobko/tap/aerospace

- name: Add FelixKratz Tap
  community.general.homebrew_tap:
    state: present
    name: FelixKratz/formulae

- name: Setup Sketchybar
  block:
    - name: Install Sketchybar
      community.general.homebrew:
        state: present
        name: FelixKratz/formulae/sketchybar

    - name: Start Sketchybar
      community.general.homebrew_services:
        state: present
        name: sketchybar


- name: Setup Jankyborders
  block:
    - name: Install Jankyborders
      community.general.homebrew:
        state: present
        name: FelixKratz/formulae/borders

    - name: Start Jankyborders
      community.general.homebrew_services:
        state: present
        name: borders

